/**
 * LinkedIn article catalog for BFP site migration.
 * slug: canonical URL slug on the site
 * linkedinPath: path segment after /pulse/
 * legacyThoughtLeadership: old /thoughtleadership/ slugs → redirect to this entry
 * legacyCaseStudy: old /case-studies/ slugs → redirect to this entry
 * localMd: optional filename in uploads/ folder
 */
export const FALLBACK_IMAGE = "/images/article-fallback.jpg";
export const AUTHOR = "Mark Vandeneijnde";

export const CATALOG = [
  {
    slug: "inner-development-goals-to-measure-or-not-2026",
    title: "Inner Development Goals: To Measure or Not to Measure?",
    date: "2026-04-08",
    type: "article",
    linkedinPath: "inner-development-goals-measure-mark-vandeneijnde-lyhue",
  },
  {
    slug: "idg-b-corp-synergy",
    title: "The Natural Synergy Between Inner Development Goals (IDGs) and B Corp",
    date: "2025-09-09",
    type: "article",
    linkedinPath: "natural-synergy-between-inner-development-goals-idgs-b-vandeneijnde-if4je",
  },
  {
    slug: "redefining-validation",
    title: "Redefining Validation: From Psychometrics to Soul Recognition",
    date: "2025-05-06",
    type: "article",
    linkedinPath: "redefining-validation-from-psychometrics-soul-mark-vandeneijnde-j0pye",
  },
  {
    slug: "siam-computing",
    title: "Strengthening Company Culture Through Inner Development Goals (IDGs)",
    date: "2024-11-20",
    type: "case-study",
    linkedinPath: "strengthening-company-culture-through-inner-idg-mark-vandeneijnde-pjqce",
  },
  {
    slug: "berlin-marathon",
    title: "Being at Full Potential: renewing a father – son relationship at the Berlin Marathon",
    date: "2024-10-23",
    type: "article",
    linkedinPath: "road-berlin-marathon-father-son-story-mark-vandeneijnde-1txme",
  },
  {
    slug: "measure-inner-development-goals",
    title: "Embracing Paradox: Measuring Inner Development Goals in Organizations",
    date: "2024-03-25",
    type: "article",
    linkedinPath: "inner-development-goals-measure-mark-vandeneijnde-beafe",
  },
  {
    slug: "diversity-equity-inclusion",
    title: "5 stages of Diversity Equity and Inclusion (DEI) consciousness",
    date: "2021-07-01",
    type: "article",
    linkedinPath: null,
  },
  {
    slug: "embedding-culture-in-ma",
    title: "3 steps to embedding the cultural dimension in the M&A due diligence process",
    date: "2021-09-22",
    type: "article",
    linkedinPath: null,
  },
  {
    slug: "leading-evolutionary-change-human-potential",
    title: "Leading Evolutionary Change in Organizations through Human Potential Realization",
    date: "2025-03-01",
    type: "article",
    linkedinPath: null,
  },
  {
    slug: "some-thoughts-future-being-full-potential",
    title: "Some Thoughts on the Future of BEING at Full Potential",
    date: "2023-11-21",
    type: "article",
    linkedinPath: "some-thoughts-future-being-full-potential-mark-vandeneijnde-4howe",
  },
  {
    slug: "retrospective-conversations-that-matter",
    title: "Retrospective: Conversations That Matter",
    date: "2023-10-31",
    type: "article",
    linkedinPath: "retrospective-conversations-matter-mark-vandeneijnde-ctzee",
  },
  {
    slug: "culture-activation-tool",
    title: "Culture Activation Tool (CAT)",
    date: "2023-10-12",
    type: "article",
    linkedinPath: "culture-activation-tool-cat-mark-vandeneijnde-f8yuf",
  },
  {
    slug: "improving-employee-experience",
    title: "Improving Employee Experience Through Workplace Transformation",
    date: "2023-08-28",
    type: "article",
    linkedinPath: "improving-employee-experience-through-workplace-mark-vandeneijnde",
  },
  {
    slug: "countering-the-threat-of-ai",
    title: "Being fully HUMAN: The Next Competitive Advantage",
    date: "2023-08-24",
    type: "article",
    linkedinPath: "being-fully-human-next-competitive-advantage-mark-vandeneijnde",
  },
  {
    slug: "learning-to-listen",
    title: "Learning to Listen in the Age of Decentralized Governance",
    date: "2023-04-18",
    type: "article",
    linkedinPath: "learning-listen-age-decentralized-governance-mark-vandeneijnde",
  },
  {
    slug: "decentralization-blockchain-human-potential",
    title: "Decentralization, Blockchain and Human Potential",
    date: "2023-02-22",
    type: "article",
    linkedinPath: "decentralization-blockchain-human-potential-mark-vandeneijnde",
  },
  {
    slug: "human-potential-model-validation",
    title: "Our Approach to Human Potential Development Validated",
    date: "2022-11-15",
    type: "article",
    linkedinPath: "our-approach-human-potential-development-validated-mark-vandeneijnde",
  },
  {
    slug: "disruptive-innovation",
    title: "3 Ways in Which Developing Human Potential Leads to Disruptive Innovation",
    date: "2021-05-04",
    type: "article",
    linkedinPath: "3-ways-which-developing-human-potential-leads-mark-vandeneijnde",
  },
  {
    slug: "world-is-vuca",
    title: "The World is VUCA: Do We Compete or Collaborate?",
    date: "2021-02-24",
    type: "article",
    linkedinPath: "world-vuca-do-we-compete-collaborate-mark-vandeneijnde",
  },
  {
    slug: "2021-source-of-trust",
    title: "In 2021, let's be each other's source of trust",
    date: "2021-01-04",
    type: "article",
    linkedinPath: "2021-lets-each-others-source-trust-mark-vandeneijnde",
  },
  {
    slug: "omega-hms",
    title: "Human Potential-Based Restructuring at Omega HMS",
    date: "2020-12-04",
    type: "case-study",
    linkedinPath: "human-potential-based-restructuring-omega-hms-mark-vandeneijnde",
    legacyThoughtLeadership: ["omega-hms-restructuring-article"],
  },
  {
    slug: "to-re-enter-workforce",
    title: "To Re-Enter the Workforce",
    date: "2020-10-23",
    type: "article",
    linkedinPath: "re-enter-workforce-mark-vandeneijnde",
  },
  {
    slug: "business-case-for-being",
    title: "The Business Case for BEING",
    date: "2020-04-24",
    type: "article",
    linkedinPath: "business-case-being-mark-vandeneijnde",
  },
  {
    slug: "human-potential-400m-opportunity",
    title: "Human Potential Realization in Organizations: A $400M Opportunity",
    date: "2019-12-06",
    type: "article",
    linkedinPath: "human-potential-realization-organizations-400m-only-vandeneijnde",
  },
  {
    slug: "synchronizing-inner-outer-worlds",
    title: "Synchronizing Inner and Outer Worlds Unleashes Human Potential",
    date: "2019-05-25",
    type: "article",
    linkedinPath: "synchronizing-inner-outer-worlds-unleashes-potential-vandeneijnde",
  },
  {
    slug: "ai-artificial-intelligence-awareness",
    title: "AI: Artificial Intelligence or Awareness Intelligence?",
    date: "2018-11-23",
    type: "article",
    linkedinPath: "ai-artificial-intelligence-awareness-mark-vandeneijnde",
  },
  {
    slug: "creating-conscious-culture-3",
    title: "Creating a Conscious Culture – Part 3",
    date: "2018-08-04",
    type: "article",
    linkedinPath: "creating-conscious-culture-part-3-mark-vandeneijnde",
    localMd: "creating-conscious-culture-part-3-mark-vandeneijnde-24.md",
  },
  {
    slug: "creating-conscious-culture-2",
    title: "Creating a Conscious Culture – Part 2",
    date: "2018-07-17",
    type: "article",
    linkedinPath: "creating-conscious-culture-part-2-mark-vandeneijnde",
    localMd: "creating-conscious-culture-part-2-mark-vandeneijnde-25.md",
  },
  {
    slug: "creating-conscious-culture-1",
    title: "Creating a Conscious Culture – Part 1",
    date: "2018-07-04",
    type: "article",
    linkedinPath: "creating-conscious-culture-part-1-mark-vandeneijnde",
  },
  {
    slug: "human-potential-realization-igniting-happiness",
    title: "Human Potential Realization: Igniting Employee Happiness",
    date: "2018-03-26",
    type: "article",
    linkedinPath: "human-potential-realization-igniting-employee-mark-vandeneijnde",
  },
  {
    slug: "creating-transformational-spaces",
    title: "Creating Transformational Spaces Within Business",
    date: "2017-12-21",
    type: "article",
    linkedinPath: "creating-transformational-spaces-within-business-5-mark-vandeneijnde",
  },
  {
    slug: "business-case-human-potential-realisation",
    title: "A compelling business case for Human Potential Realisation",
    date: "2017-06-22",
    type: "case-study",
    linkedinPath: "business-case-human-potential-realisation-mark-vandeneijnde",
    localMd: "business-case-human-potential-realisation-mark-vandeneijnde-0.md",
    legacyCaseStudy: ["thorntons-budgens"],
  },
  {
    slug: "accessing-innovation-human-potential",
    title: "Accessing Innovation the Human Potential Way",
    date: "2017-02-28",
    type: "article",
    linkedinPath: "accessing-innovation-human-potential-way-mark-vandeneijnde",
    legacyThoughtLeadership: [
      "accessing-higher-states-of-awareness",
      "shifting-innovation-inside-out",
    ],
  },
  {
    slug: "from-sustainability-to-thrive-ability-3",
    title: "From Sustainability to Thrive-Ability – Part 3: How to Build Thrive-Ability",
    date: "2016-12-12",
    type: "article",
    linkedinPath: "from-sustainability-thrive-ability-part-3-how-build-vandeneijnde",
  },
  {
    slug: "from-sustainability-to-thrive-ability-2",
    title: "From Sustainability to Thrive-Ability – Part 2: Why Is It So Hard?",
    date: "2016-12-05",
    type: "article",
    linkedinPath: "from-sustainability-thrive-ability-part-2-why-so-mark-vandeneijnde",
  },
  {
    slug: "from-sustainability-to-thrive-ability-1",
    title: "From Sustainability to Thrive-Ability – Part 1: Assessing Your Thrive-Ability",
    date: "2016-11-30",
    type: "article",
    linkedinPath: "from-sustainability-thrive-ability-part-1-assessing-vandeneijnde",
  },
  {
    slug: "lessons-in-thrive-ability",
    title: "Lessons in Thrive-Ability from the French Countryside",
    date: "2016-08-30",
    type: "article",
    linkedinPath: "lessons-thrive-ability-from-french-countryside-mark-vandeneijnde",
  },
  {
    slug: "seven-lessons-keeping-heart-alive",
    title: "How to Keep the Heart in Your Business Alive: Seven Lessons from the Past",
    date: "2016-01-07",
    type: "article",
    linkedinPath: "how-keep-heart-your-business-alive-seven-lessons-past-vandeneijnde",
  },
];

/** All slugs from the previous WordPress-era article-content.json */
export const LEGACY_SLUGS = [
  "23-ways-to-express-human-potential",
  "4-types-of-organizational-change",
  "5-keys-to-google-team",
  "6-organizational-performance-metrics",
  "8-characteristics-soulful-organization",
  "accessing-higher-states-of-awareness",
  "action-logics-across-generations",
  "ai-artificial-intelligence-awareness",
  "back-to-home-base",
  "being-human-at-work",
  "berlin-marathon",
  "business-case-for-being",
  "conscious-culture-presentation",
  "countering-the-threat-of-ai",
  "creating-conscious-culture-1",
  "creating-conscious-culture-2",
  "creating-conscious-culture-3",
  "creating-transformational-spaces",
  "daring-greatly-in-the-classroom",
  "decentralization-blockchain-human-potential",
  "disruptive-innovation",
  "diversity-equity-inclusion",
  "embedding-culture-in-ma",
  "employability-future-of-work",
  "evidence-based-strategies",
  "evolving-leadership-consciousness",
  "from-sustainability-to-thrive-ability-3",
  "gap-in-employee-well-being",
  "gift-of-self-compassion",
  "human-potential-400m-opportunity",
  "human-potential-methodology-org-transformation",
  "human-potential-model-validation",
  "human-potential-realization-igniting-happiness",
  "human-potential-realization-starts-at-home-1",
  "human-potential-realization-starts-at-home-2",
  "humanitys-inner-development",
  "idg-b-corp-synergy",
  "impact-at-individual-level-marta",
  "impact-at-team-level-cto",
  "improving-employee-experience",
  "inner-development-goals-to-measure-or-not-2026",
  "leadership-development-366-billion",
  "leadership-methods-future-proof",
  "learning-to-listen",
  "lessons-in-thrive-ability",
  "measure-inner-development-goals",
  "od-work-in-breakdown",
  "omega-hms",
  "omega-hms-restructuring-article",
  "organizational-change-management",
  "redefining-validation",
  "reflections-on-2021",
  "retrospective-conversations-that-matter",
  "roi-of-boosting-employee-engagement",
  "shifting-innovation-inside-out",
  "siam-computing",
  "synchronizing-inner-outer-worlds",
  "thorntons-budgens",
  "to-re-enter-workforce",
  "transformational-leaders-2020",
  "un-sustainability-of-sustainability-departments",
  "world-is-vuca",
];
